- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Docker SDK and dependencies
  pip:
    name:
      - docker==6.1.3
      - docker-compose==1.29.2
      - urllib3<2
      - requests
      - docker-pycreds
    executable: pip3
  become: true

- name: Ensure python3-pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install docker Python module
  pip:
    name: docker
    executable: pip3

- name: Create Plex project directory
  file:
    path: /opt/plex
    state: directory
    owner: "{{ ansible_user | default('charles') }}"
    group: "{{ ansible_user | default('charles') }}"
    mode: '0755'

- name: Copy Plex docker-compose file
  copy:
    src: roles/plex/files/docker-compose.yml
    dest: /opt/plex/docker-compose.yml
    mode: '0644'

- name: Launch Plex with Docker Compose V2
  community.docker.docker_compose_v2:
    project_src: /opt/plex
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
    PLEX_CLAIM: "{{ plex_claim | default('') }}"
  become: true

